baseURL: "https://mbrykow.github.io/" 
title: Marissa B. Rykowski
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: CV
          url: CV/
          weight: 5 
        - name: Dissertation
          url: Dissertation/
          weight: 5 
        #- name: Data
          #url: Data/
          #weight: 4 
        - name: TidyTuesday
          url: TidyTuesday/
          weight: 3 

params:
    description: "This website hosts Marissa B. Rykowski's dissertation, data, curriculum vitae, and contact information."
    author: Marissa B. Rykowski
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["CV","Dissertation","Data","TidyTuesday"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Dr. Marissa B. Rykowski, Ph.D.
          subtitle: "A recent Ph.D. graduate looking for a position in data science, statistical programming, and/or fisheries science. Proven ability to apply advanced statistical methods to complex datasets, with a focus on protected and endangered species. Proficient in statistical software (R) and data visualization tools. Eager to contribute to innovative projects in data analytics and ecological research, aiming to drive impactful solutions in the environmental sector."
          imageUrl: "BeachHeadshot_edit.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: CV
              url: "RykowskiMB_CV.pdf"
            - name: Dissertation
              url: https://scholarship.miami.edu/esploro/outputs/doctoral/Assessing-Threats-from-Global-Warming-and/991032489071302976?institution=01UOML_INST
            #- name: Data
              #url: Data/
            - name: TidyTuesday
              url: TidyTuesday/

    socialIcons:
        - name: Email
          url: mailto:mbrykow@gmail.com
        #- name: Google Scholar
          #url:
        - name: LinkedIn
          url: https://www.linkedin.com/in/marissa-rykowski-015167122/
        - name: GitHub
          url: https://github.com/mbrykow

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Marissa B. Rykowski"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2